# kind config file:
# nodes:
#  - role: control-plane
#    image: "kindest/node:v1.31.4"
#    labels:
#      ingress-ready: "true"
#    extraPortMappings:
#      - containerPort: 443
#        hostPort: 8443
#        listenAddress: "127.0.0.1"
#        protocol: TCP

kind:
  name: kind
  kubernetesVersion: v1.29.4 #  See versions of the kind project: https://github.com/kubernetes-sigs/kind/releases/tag/v0.27.0
  labels: "ingress-ready=true"
  providerId: podman # podman or docker
  bindings:
  - containerPort: 443
    hostPort: 8443
  - containerPort: 32222
    hostPort: 32222