name: Dummy release

on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]
    paths:
      - '.github/project.yml'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  maven-release:
    runs-on: ubuntu-latest
    name: Release java-kind-client
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true}}
    outputs:
      already_released: ${{steps.released.outputs.already_released}}

    steps:
      - uses: actions/checkout@v4

      - uses: radcortez/project-metadata-action@main
        name: Retrieve project metadata
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'
          local-file: true

      - name: Check if already released
        id: released
        run: |
          # TODO
          # if curl --output /dev/null --silent --head --fail "https://repo1.maven.org/maven2/net/laprun/sustainability/java-kind-client/${{steps.metadata.outputs.current-version}}"; then
          #  echo "already_released=true" >> $GITHUB_OUTPUT
          #fi
          echo "already_released=false" >> $GITHUB_OUTPUT

  # Collect all executables and release
  release:
    if: needs.maven-release.outputs.already_released != 'true'
    needs: [ maven-release ]
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # checkout will clobber downloaded artifacts
      # we have to download them again
      #- name: 'Download all build artifacts'
      #  uses: actions/download-artifact@v4
      #  with:
      #    path: artifacts
      #    pattern: jkind-*
      #    merge-multiple: true
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v10
        with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            run_id: 15489296318
            path: artifacts
            name: jkind-macOS-ARM64
            #https://github.com/halkyonio/java-kind-client/actions/runs/15489296318/artifacts/3275274968
            #sha256: 8d9297ddfd927580db9767406b9608223d80a9c7dc4f2dff512f6e402517de6e
            #OUTPUT_FILENAME="jkind-macOS-ARM64.zip"

      - name: 'Set up Java'
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: 'Release with JReleaser'
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -ntp -B --file pom.xml -Prelease -DartifactsDir=artifacts jreleaser:full-release

      - name: 'JReleaser output'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jreleaser-logs
          path: |
            target/jreleaser/trace.log
            target/jreleaser/output.properties
