name: CI to build the executable

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #        os: [windows-latest, macos-latest, ubuntu-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Checkout the Platform Operator Maven project
      uses: actions/checkout@v4
      with:
        repository: halkyonio/java-package-operator
        path: java-package-operator

    - name: Package the Platform Operator Maven project
      working-directory: java-package-operator
      run: mvn -B install -DskipTests

    - name: 'Build project'
      run: mvn -B clean install -DskipTests -Dno-format

    - name: 'Build Native Image'
      run: |
        mvn -B clean install -Dnative -Dquarkus.native.container-build -Dnative.surefire.skip
        ls -la target
        ls -la target/distributions

    - name: 'Upload build artifact'
      uses: actions/upload-artifact@v4
      with:
        name: jkind-${{ runner.os }}-${{ runner.arch }}
        path: target/distributions/*.tar.gz