name: Java CI to build the executable

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        native-image-job-reports: 'true'

    - name: 'Build project'
      run: mvn install -DskipTests

    - name: 'Build Native Image'
      run: |
        mvn -ntp -B -Pnative package -DskipTests

    - name: 'Create distribution'
      run: |
        mvn -ntp -B -Pdist package -DskipTests

    - name: 'Upload build artifact'
      uses: actions/upload-artifact@v4
      with:
        name: jkind-${{ runner.os }}-${{ runner.arch }}
        path: target/distributions/*.tar.gz