name: CI to build the executable

on:
  workflow_dispatch:
    inputs:
      platform:
        required: false
        description: Binary platform
        type: string
        default: "macOS-latest"
  workflow_call:
    inputs:
      platform:
        required: false
        description: Binary platform
        type: string
        default: "macOS-latest"

jobs:
  build:
    name: 'Build with Graal on ${{ inputs.platform }}'
    runs-on: ${{ inputs.platform }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Setup graalvm
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        native-image-job-reports: 'true'

    - name: Checkout the Platform Operator Maven project
      uses: actions/checkout@v4
      with:
        repository: halkyonio/java-package-operator
        path: java-package-operator

    - name: Package the Platform Operator Maven project
      working-directory: java-package-operator
      run: mvn -B install -DskipTests

    - name: 'Build project'
      run: mvn -B clean install -DskipTests -Dno-format

    - name: 'Build Native Image'
      run: |
        mvn -ntp -B clean install -Pnative -DskipTests

    - name: 'Create distribution'
      run: |
        mvn -ntp -B --file pom.xml -Pdist package -DskipTests

    - name: 'Upload build artifact'
      uses: actions/upload-artifact@v4
      with:
        name: jkind-${{ runner.os }}-${{ runner.arch }}
        path: target/distributions/*.tar.gz